import "server-only";
import {
  Circle,
  Document,
  Page,
  Path,
  StyleSheet,
  Svg,
  Text,
  View,
} from "@react-pdf/renderer";
import type {
  Finding,
  StoredSections,
  TimelineEntry,
} from "@/lib/ai/schemas";

const COLORS = {
  text: "#1e293b",
  muted: "#64748b",
  border: "#e2e8f0",
  primary: "#2563eb",
  low: "#059669",
  medium: "#d97706",
  high: "#e11d48",
  info: "#2563eb",
  warning: "#d97706",
  danger: "#e11d48",
};

const RISK_COLOR: Record<StoredSections["riskLevel"], string> = {
  low: COLORS.low,
  medium: COLORS.medium,
  high: COLORS.high,
};

const SEVERITY_COLOR: Record<Finding["severity"], string> = {
  info: COLORS.info,
  warning: COLORS.warning,
  danger: COLORS.danger,
};

const CONTRACT_TYPE_LABELS: Record<StoredSections["contractType"], string> = {
  tenancy: "Tenancy agreement",
  employment: "Employment contract",
  freelance: "Freelance agreement",
  nda: "NDA",
  other: "Other agreement",
};

const FINDING_SECTIONS: { key: keyof StoredSections["findings"]; label: string }[] = [
  { key: "hiddenRisks", label: "Hidden Risks" },
  { key: "importantClauses", label: "Important Clauses" },
  { key: "financialObligations", label: "Financial Obligations" },
  { key: "terminationClauses", label: "Termination Clauses" },
  { key: "cancellationRules", label: "Cancellation Rules" },
];

const styles = StyleSheet.create({
  page: {
    padding: 40,
    paddingBottom: 56,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: COLORS.text,
  },
  coverPage: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    padding: 60,
  },
  coverTitle: {
    fontSize: 24,
    fontFamily: "Helvetica-Bold",
    marginTop: 24,
    textAlign: "center",
  },
  coverType: {
    fontSize: 12,
    color: COLORS.muted,
    marginTop: 8,
  },
  coverDate: {
    fontSize: 10,
    color: COLORS.muted,
    marginTop: 4,
  },
  riskBadge: {
    marginTop: 28,
    paddingVertical: 8,
    paddingHorizontal: 18,
    borderRadius: 999,
  },
  riskBadgeText: {
    color: "#ffffff",
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
  },
  h1: {
    fontSize: 15,
    fontFamily: "Helvetica-Bold",
    marginTop: 18,
    marginBottom: 8,
  },
  h2: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    marginTop: 12,
    marginBottom: 4,
  },
  paragraph: {
    fontSize: 10,
    lineHeight: 1.5,
    color: COLORS.text,
  },
  findingBlock: {
    marginBottom: 8,
    paddingLeft: 10,
    borderLeftWidth: 2,
  },
  findingTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
  },
  findingExplanation: {
    fontSize: 9.5,
    color: COLORS.muted,
    lineHeight: 1.4,
    marginTop: 2,
  },
  factRow: {
    flexDirection: "row",
    marginBottom: 6,
  },
  factLabel: {
    width: 110,
    fontFamily: "Helvetica-Bold",
    fontSize: 10,
  },
  factValue: {
    flex: 1,
    fontSize: 10,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    paddingVertical: 6,
  },
  tableHeaderRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: COLORS.text,
    paddingBottom: 4,
    marginBottom: 2,
  },
  tableCellDate: { width: 70, fontSize: 9 },
  tableCellLabel: { width: 130, fontSize: 9, fontFamily: "Helvetica-Bold" },
  tableCellType: { width: 70, fontSize: 9, color: COLORS.muted },
  tableCellExplanation: { flex: 1, fontSize: 9, color: COLORS.muted },
  questionRow: {
    flexDirection: "row",
    marginBottom: 5,
  },
  questionIndex: {
    width: 18,
    fontFamily: "Helvetica-Bold",
    fontSize: 10,
  },
  questionText: {
    flex: 1,
    fontSize: 10,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 8,
    color: COLORS.muted,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingTop: 8,
  },
});

function LogoMark() {
  return (
    <Svg width={40} height={40} viewBox="0 0 32 32">
      <Path
        d="M7 5a3 3 0 0 1 3-3h8.5L25 8.5V27a3 3 0 0 1-3 3H10a3 3 0 0 1-3-3V5Z"
        fill="none"
        stroke={COLORS.primary}
        strokeWidth={2}
      />
      <Path
        d="M18.5 2v5a2 2 0 0 0 2 2H25"
        fill="none"
        stroke={COLORS.primary}
        strokeWidth={2}
      />
      <Circle cx={15} cy={17} r={4.5} fill="none" stroke={COLORS.primary} strokeWidth={2} />
      <Path d="m18.5 20.5 3.5 3.5" stroke={COLORS.primary} strokeWidth={2} />
    </Svg>
  );
}

function Footer() {
  return (
    <View style={styles.footer} fixed>
      <Text>Generated by ContractLens AI — not legal advice</Text>
      <Text
        render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
      />
    </View>
  );
}

function FindingsGroup({ label, items }: { label: string; items: Finding[] }) {
  return (
    <View wrap={false}>
      <Text style={styles.h2}>
        {label} ({items.length})
      </Text>
      {items.length === 0 ? (
        <Text style={[styles.findingExplanation, { marginBottom: 8 }]}>
          Nothing flagged in this category.
        </Text>
      ) : (
        items.map((item, i) => (
          <View
            key={i}
            style={[styles.findingBlock, { borderLeftColor: SEVERITY_COLOR[item.severity] }]}
          >
            <Text style={styles.findingTitle}>{item.title}</Text>
            <Text style={styles.findingExplanation}>{item.explanation}</Text>
          </View>
        ))
      )}
    </View>
  );
}

export interface PdfReportProps {
  title: string;
  createdAt: string;
  riskScore: number;
  summary: string;
  sections: StoredSections;
  timeline: TimelineEntry[];
  recommendedQuestions: string[];
}

export function ContractPdfReport({
  title,
  createdAt,
  riskScore,
  summary,
  sections,
  timeline,
  recommendedQuestions,
}: PdfReportProps) {
  const riskColor = RISK_COLOR[sections.riskLevel];
  const dateLabel = new Date(createdAt).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  return (
    <Document title={`${title} — ContractLens AI analysis`}>
      <Page size="A4" style={styles.page}>
        <View style={styles.coverPage}>
          <LogoMark />
          <Text style={styles.coverTitle}>{title}</Text>
          <Text style={styles.coverType}>{CONTRACT_TYPE_LABELS[sections.contractType]}</Text>
          <Text style={styles.coverDate}>{dateLabel}</Text>
          <View style={[styles.riskBadge, { backgroundColor: riskColor }]}>
            <Text style={styles.riskBadgeText}>
              Risk score: {riskScore} / 100 ({sections.riskLevel.toUpperCase()})
            </Text>
          </View>
        </View>
        <Footer />
      </Page>

      <Page size="A4" style={styles.page}>
        <Text style={styles.h1}>Summary</Text>
        <Text style={styles.paragraph}>{summary}</Text>

        <Text style={styles.h1}>Risk breakdown</Text>
        <Text style={styles.paragraph}>{sections.riskExplanation}</Text>

        <Text style={styles.h1}>Findings</Text>
        {FINDING_SECTIONS.map((section) => (
          <FindingsGroup
            key={section.key}
            label={section.label}
            items={sections.findings[section.key]}
          />
        ))}

        <Text style={styles.h1}>Notice Period &amp; Auto-Renewal</Text>
        <View style={styles.factRow}>
          <Text style={styles.factLabel}>Notice period</Text>
          <Text style={styles.factValue}>
            {sections.noticePeriod.value ?? "Not specified"} — {sections.noticePeriod.explanation}
          </Text>
        </View>
        <View style={styles.factRow}>
          <Text style={styles.factLabel}>Auto-renewal</Text>
          <Text style={styles.factValue}>
            {sections.autoRenewal.present ? "Yes" : "No"} — {sections.autoRenewal.explanation}
          </Text>
        </View>

        <Text style={styles.h1}>Missing Clauses</Text>
        {sections.missingClauses.length === 0 ? (
          <Text style={styles.paragraph}>None identified.</Text>
        ) : (
          sections.missingClauses.map((clause, i) => (
            <View key={i} style={[styles.findingBlock, { borderLeftColor: COLORS.warning }]}>
              <Text style={styles.findingTitle}>{clause.title}</Text>
              <Text style={styles.findingExplanation}>{clause.whyItMatters}</Text>
            </View>
          ))
        )}

        <Text style={styles.h1}>Timeline</Text>
        {timeline.length === 0 ? (
          <Text style={styles.paragraph}>No dated events identified.</Text>
        ) : (
          <View>
            <View style={styles.tableHeaderRow}>
              <Text style={styles.tableCellDate}>Date</Text>
              <Text style={styles.tableCellLabel}>Event</Text>
              <Text style={styles.tableCellType}>Type</Text>
              <Text style={styles.tableCellExplanation}>Details</Text>
            </View>
            {timeline.map((entry, i) => (
              <View key={i} style={styles.tableRow} wrap={false}>
                <Text style={styles.tableCellDate}>
                  {entry.date
                    ? new Date(entry.date).toLocaleDateString("en-GB", {
                        day: "numeric",
                        month: "short",
                        year: "numeric",
                      })
                    : "Not specified"}
                </Text>
                <Text style={styles.tableCellLabel}>{entry.label}</Text>
                <Text style={styles.tableCellType}>{entry.type}</Text>
                <Text style={styles.tableCellExplanation}>{entry.explanation}</Text>
              </View>
            ))}
          </View>
        )}

        <Text style={styles.h1}>Recommended Questions</Text>
        {recommendedQuestions.map((question, i) => (
          <View key={i} style={styles.questionRow} wrap={false}>
            <Text style={styles.questionIndex}>{i + 1}.</Text>
            <Text style={styles.questionText}>{question}</Text>
          </View>
        ))}

        <Footer />
      </Page>
    </Document>
  );
}
